# Generated by Django 3.2.12 on 2022-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='contact_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
