# Generated by Django 3.2.12 on 2022-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0003_auto_20220414_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending Approval'), (2, 'Approved'), (3, 'Not Approved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending Approval'), (2, 'Approved'), (3, 'Not Approved')], default=2, null=True),
        ),
    ]
