# Generated by Django 3.2.12 on 2022-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0004_auto_20220414_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Not Approved'), (1, 'Pending Approval'), (2, 'Approved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qr_image',
            field=models.ImageField(null=True, upload_to='staffs/qr'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Not Approved'), (1, 'Pending Approval'), (2, 'Approved')], default=2, null=True),
        ),
    ]
