# Generated by Django 3.2.12 on 2022-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_registration', '0006_auto_20220418_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Approved'), (1, 'Pending Approval'), (3, 'Not Approved')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='is_approved',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Approved'), (1, 'Pending Approval'), (3, 'Not Approved')], default=2, null=True),
        ),
    ]
